dataset:
  global_sampling_rate: null
  global_chunk_size: null
  add_behavior_as_channels: False
  replace_nans_with_means: False
  cache_data: False
  modality_config:
    screen:
      keep_nans : False
      sampling_rate: 30
      chunk_size: 60
      valid_condition:
        tier: "train"
      offset: 0
      sample_stride: 1
      include_blanks: True
      transforms:
        normalization: "screen_default"
      interpolation:
        rescale: True
        rescale_size: [36, 64]
    responses:
      keep_nans : False
      sampling_rate: 8
      chunk_size: 16
      offset: 0.0 # in seconds
      transforms:
        normalization: "recompute_responses"
      interpolation:
        interpolation_mode: "nearest_neighbor"
      filters:
        nan_filter:
          __target__: experanto.filters.common_filters.nan_filter
          __partial__: True
          vicinity: 0.05
        # artifact_filter:
        #   __target__: experanto.filters.responses_filters.artifact_filter
        #   __partial__: True
        #   vicinity: 0.05
    eye_tracker:
      keep_nans : False
      sampling_rate: 30
      chunk_size: 60
      offset: 0
      transforms:
        normalization: "recompute_behavior"
      interpolation:
        interpolation_mode: "nearest_neighbor"
      filters:
        nan_filter:
          __target__: experanto.filters.common_filters.nan_filter
          __partial__: True
          vicinity: 0.05
    treadmill:
      keep_nans : False
      sampling_rate: 30
      chunk_size: 60
      offset: 0
      transforms:
        normalization: "recompute_behavior"
      interpolation:
        interpolation_mode: "nearest_neighbor"
      filters:
        nan_filter:
          __target__: experanto.filters.common_filters.nan_filter
          __partial__: True
          vicinity: 0.05

dataloader:
  batch_size: 16
  shuffle: true
  num_workers: 2
  pin_memory: True
  drop_last: True
  prefetch_factor: 2
  shuffle_each_epoch: False



